<?php $this->partial('shared/header'); ?>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    Total result: <span id="params-total"><?= number_format($total, 0, '.', '.') ?></span>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="page-header">
                <h3>Installed Modules</h3>
                
            </div>
                
            <?php if($modules): ?>
            
            <div class="list-group">
                <?php foreach($modules as $mod): ?>
                <div class="list-group-item">
                    
                    <h4 class="list-group-item-heading"><?= $mod->__name ?> <small>v<?= $mod->__version ?></small></h4>
                    <p class="list-group-item-text small">
                        <span title="Repository"><i class="fa fa-git" aria-hidden="true"></i><?= $mod->__git ?></span>
                    </p>
                </div>
                <?php endforeach; ?>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>

<?php $this->partial('shared/footer'); ?>